# Generated by Django 4.0.6 on 2022-08-01 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Kpk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название курсов в соответствии с удостоверением')),
                ('city', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Город')),
                ('organization', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Организация в соответствии с удостоверением')),
                ('date_issue', models.DateField(blank=True, max_length=1000, null=True, verbose_name='Дата выдачи')),
                ('number_hours', models.IntegerField(blank=True, null=True, verbose_name='Количество часов')),
                ('default_view', models.BooleanField(default=False, verbose_name='Показывать по умолчанию')),
            ],
            options={
                'verbose_name': 'КПК',
                'verbose_name_plural': 'КПК',
            },
        ),
        migrations.CreateModel(
            name='ProfileShifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Профильная смена',
                'verbose_name_plural': 'Профильные смены',
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название публиации')),
                ('name_journal', models.CharField(max_length=1000, verbose_name='Название журнала / сборника')),
                ('city', models.CharField(max_length=1000, verbose_name='Город исздательства')),
                ('page_range', models.CharField(max_length=1000, verbose_name='Диапазон страниц')),
            ],
            options={
                'verbose_name': 'Публикации',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('date_from', models.DateField(max_length=250, verbose_name='Дата с')),
                ('date_to', models.DateField(max_length=250, verbose_name='Дата по')),
                ('level', models.CharField(choices=[('0', 'Муниципальный'), ('1', 'Региональный'), ('2', 'Федеральный')], default='0', max_length=1, verbose_name='Уровень')),
                ('category_document', models.FileField(upload_to='documents/')),
                ('result', models.CharField(choices=[('0', 'Победитель'), ('1', 'Призер'), ('2', 'Участник')], default='2', max_length=1, verbose_name='Результат')),
                ('kpk_document', models.FileField(upload_to='documents/')),
                ('publications_document', models.FileField(upload_to='documents/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categories')),
                ('kpk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kpk')),
                ('publications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.publications')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subcategories')),
            ],
            options={
                'verbose_name': 'Данные об учителе',
                'verbose_name_plural': 'Данные об учителе',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('date_from', models.DateField(max_length=250, verbose_name='Дата с')),
                ('date_to', models.DateField(max_length=250, verbose_name='Дата по')),
                ('level', models.CharField(choices=[('0', 'Муниципальный'), ('1', 'Региональный'), ('2', 'Федеральный')], default='0', max_length=1, verbose_name='Уровень')),
                ('document', models.FileField(upload_to='documents/')),
                ('result', models.CharField(choices=[('0', 'Победитель'), ('1', 'Призер'), ('2', 'Участник')], default='2', max_length=1, verbose_name='Результат')),
                ('name_program', models.CharField(max_length=1000, verbose_name='Название программы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categories')),
                ('participation_in_profile_shifts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profileshifts')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subcategories')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные об ученике',
                'verbose_name_plural': 'Данные об учениках',
            },
        ),
    ]
