# Generated by Django 4.0.6 on 2022-07-14 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProfileShifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Профильная смена',
                'verbose_name_plural': 'Профильные смены',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('participation_period', models.CharField(max_length=250, verbose_name='Период участия')),
                ('mounth', models.CharField(choices=[('0', 'Январь'), ('1', 'Февраль'), ('2', 'Март'), ('3', 'Апрель'), ('4', 'Май'), ('5', 'Июнь'), ('6', 'Июль'), ('7', 'Август'), ('8', 'Сентябрь'), ('9', 'Октябрь'), ('10', 'Ноябрь'), ('11', 'Декабрь')], default='0', max_length=2, verbose_name='Месяц')),
                ('level', models.CharField(choices=[('0', 'Муниципальный'), ('1', 'Региональный'), ('2', 'Федеральный')], default='0', max_length=1, verbose_name='Уровень')),
                ('document', models.FileField(upload_to='documents/')),
                ('result', models.CharField(choices=[('0', 'Победитель'), ('1', 'Призер'), ('2', 'Участник')], default='2', max_length=1, verbose_name='Результат')),
                ('name_program', models.CharField(max_length=1000, verbose_name='Название программы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categories')),
                ('participation_in_profile_shifts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profileshifts')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные об ученике',
                'verbose_name_plural': 'Данные об учениках',
            },
        ),
    ]
