# Generated by Django 4.0.6 on 2022-07-16 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_students_result_alter_students_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subcategories', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='students',
            name='participation_in_profile_shifts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profileshifts', verbose_name='Участие в профильных сменах'),
        ),
        migrations.AlterField(
            model_name='students',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель-наставник'),
        ),
    ]
